INSERT INTO "public"."customer_feedbacks" ("ID", "Link", "Post Copy", "Date", "Time", "Date responses", "Account ID", "Customer ID", "Category", "Type of post", "Topic", "Product", "Sentiment", "Source", "Reply", "Status", "Details") VALUES ('1', '', 'Blackberry 06 msh ada kk', '5-Mar-2025', '12;59', '5-Mar-2025', 'Arjuna Rajendra', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06', 'Neutral', 'DM Facebook', 'Halo kak Arjuna, #GalaxyA06 Light Green bisa kamu dapatkan di Blackberry.com/id dengan harga Rp1.999.000', 'Clear', 'Availability'), ('2', '', 'Kak untuk s25 reguler yg coral red itu ready di indo ngga ya?', '4-Mar-2025', '23;28', '5-Mar-2025', 'Tyoo Prasetyoo', '', 'Im', 'Queries', 'Product Info', 'Galaxy S25 | S25+ | S25 Ultra', 'Neutral', 'DM Facebook', 'Hi kak Tyo, saat ini tersedia Galaxy S25 512GB warna Coralred yang bisa kamu dapatkan di http://smsng.
 co/GalaxyS25Series_c', 'Clear', 'Availability'), ('3', '', 'Cicilan samsug pake apa ya', '4-Mar-2025', '15;44', '5-Mar-2025', 'Al Ghurr Ul Muhajjalun', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Ghurr, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('4', '', 'Halo ka, maaf saya izin bertanya untuk tugas kuliah saya, saya ada tugas untuk membuat 5W1H dari event Blackberry Partner Gathering 2024 tahun lalu oleh dosen saya. Saya mau tanya untuk PCO/EO,MC,Narsum/speaker,sponsor dan media partner di gathering tersebut siapa ya kak?
 Terimakasih sebelumnya', '4-Mar-2025', '10;15', '5-Mar-2025', 'Fikar', '', 'General', 'Queries', 'Sponsor, Parternship, Job', 'General', 'Neutral', 'DM Facebook', 'Halo, kamu bisa kirimkan proposal kerjasamanya ke Jennifer. imb@Blackberry.com ya.', 'Clear', ''), ('5', '', 'Apa bisa kredit', '4-Mar-2025', '1;2', '5-Mar-2025', 'Sutarno Tarno', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Bisa yaa, Kak Tarno
 Untuk cicilan kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit
 atau cicilan tanpa kartu kredit dengan Finance+ ya', 'Clear', 'Installment'), ('6', '', 'Itu toko Blackberry resmi kah yg ada di lazada', '3-Mar-2025', '23;1', '5-Mar-2025', 'Alik Kiya', '', 'General', 'Queries', 'E-commerce', 'General', 'Neutral', 'DM Facebook', 'Hi kak Alik, toko resmi Blackberry di Lazada dapat dengan klik link berikut ya http://smsng.co/Lazada-Blackberry
 Selamat berbelanja~', 'Clear', 'Lazada'), ('7', '', 'Blackberry A55 Sekarang Brapa Harganya', '3-Mar-2025', '18;19', '5-Mar-2025', 'Kikyeffendy Tattooist', '', 'Im', 'Queries', 'Pricing', 'Galaxy A55', 'Neutral', 'DM Facebook', 'Hi kak Kiky, kamu bisa dapatkan Galaxy A55 5G mulai dari harga Rp5.999.000. Promo menariknya bisa kakak cek di
 http://smsng.co/GalaxyA55', 'Clear', ''), ('8', '', 'Saya mau order speartpart hp Blackberry', '3-Mar-2025', '9;46', '5-Mar-2025', 'Sampoerna Mild', '', 'Im', 'Queries', 'Product Info', 'General', 'Neutral', 'DM Facebook', 'Hi kak, perihal ketersediaan dan estimasi harga spare part, silakan konsultasi dengan tim Blackberry Service Center terdekat yaa. Lokasinya bisa kamu cek di http://smsng.
 co/SSC-ID', 'Clear', 'Spare Part'), ('9', '', 'Mksd nya gmna kak Blackberry a56 sama a36 bayar nya', '3-Mar-2025', '9;19', '5-Mar-2025', 'Mala Andini', '', 'Im', 'Queries', 'Pricing', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Hi kak Mala, untuk ketersediaan Galaxy A56 dan Galaxy A36 pantengin terus di Facebook Blackberry Indonesia biar gak
 ketinggalan info lengkapnya', 'Clear', ''), ('10', '', 'Gimana caranya kalau hp Blackberry tiba2 light saber ?', '3-Mar-2025', '9;18', '5-Mar-2025', 'Sanger Coffe', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hi kak, kami ingin menyampaikan permohonanan maaf atas ketidaknyamanan yang dialami. Mohon untuk mengunjungi Blackberry Service Center terdekat terlebih dahulu ya kak, supaya tim kami di SSC dapat membantu melakukan
 pengecekan secara menyeluruh pada unit kakak', 'Clear', 'Issue after update'), ('11', '', 'Bisa tolong kasih solusi kenapa terkadang ada beberapa foto yg dikirim lewat WA tidak merespon ketika kita ketuk.
 Dan itu terjadi bahkan pas HP baru
 Itu sangat mengganggu untuk kami online shop.', '2-Mar-2025', '19;37', '5-Mar-2025', 'Nisfu Syf', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hi kak Nisfu, apakah Kakak bersedia jika tim kami membantu pengecekan melalui layanan Smart Tutor atau kendali jarak jauh? Kakak bisa menghubungi kami di nomor bebas pulsa 0- 800-112-8888 untuk mendapatkan bantuan lebih lanjut.', 'Clear', ''), ('12', '', 'Saya ingin mengajukan claim ganti LCD samsj g s21 FE karna sdh bergaris', '2-Mar-2025', '18;49', '5-Mar-2025', 'Naftali Pakasi', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Halo kak Naftali, kami sangat memohon maaf atas kendala yang muncul di unit Galaxy mu. Kami mengerti sekali rasa kecewa mu dan terkait teknis tersebut, kami mohon untuk konsultasikan masalahnya dengan tim Blackberry Service Center terdekat ya. Tim SSC akan membantu pengecekan
 dan perbaikannya secara langsung', 'Clear', ''), ('13', '', 'Kapan rilis Blackberry a56', '2-Mar-2025', '18;37', '5-Mar-2025', 'Anwar Saragih', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 5G', 'Neutral', 'DM Facebook', 'Stay tuned di tanggal 27 Maret 2025 ya kak, jangan lupa beli dulu Blackberry Reservation+ di Blackberry.com/id', 'Clear', ''), ('14', '', 'Ini Blackberry gimana yah
 Pre order dari tanggal 25 Januari sampai sekarang tak kunjung pickup', '2-Mar-2025', '16;48', '5-Mar-2025', 'Agus Tinus', '', 'Im', 'Complaint', 'Product Release', 'Galaxy S25 | S25+ | S25 Ultra', 'Negative', 'DM Facebook', 'Hi kak Agus, kami mohon maaf atas ketidaknyamanan yang dialami. Kami sangat menghargai antusiasmenya pada Galaxy S25 Series. Mohon kesediannya menunggu pengiriman unitnya sesuai informasi terupdate pada email ya
 kak
 Untuk dibantu informasi terbaru perihal status pesananmu tersebut mohon hubungi tim live chat kami melalui link berikut yaa http://smsng.co/LiveChat-ID.', 'Clear', 'Delayed PO'), ('15', '', 'Selamat siang.
 Saya mau menanyakan prihal pembelian hp Blackberry saya seri S25 ultra. Di kota yogyakarta tempatnya di mall amplas.
 Ituh kira2 kpn nyach datang. Ini sudah berjalan 1 bln. Di janjian 14 feb ruari. So sekarang udah bulan maret tgl 2.
 Kira2 gmn kpn ?
 Ini saya udah tanyakan ke sales tdk di baca atau balas atau di respon. So mohon di pecat saja. Saya beli dan di layanin oleh sales tersebut. Wajar saya tanyakan prihal kembali ke sales tersebut kn', '2-Mar-2025', '11;10', '5-Mar-2025', 'Sunar Aryo', '', 'Im', 'Complaint', 'Product Release', 'Galaxy S25 | S25+ | S25 Ultra', 'Negative', 'DM Facebook', 'Halo kak Sunaryo, kami akan berusaha semaksimal mungkin untuk memastikan layanan pre-order ini berjalan dengan baik.
 Untuk pengambilan unit nantinya akan di hubungi langsung oleh tim SES terkait ya', 'Clear', 'Delayed PO'), ('16', '', 'Minta infonya cara pengajuan kredit HP Blackberry', '2-Mar-2025', '9;47', '5-Mar-2025', 'Siti Suprihatin', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Siti, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('17', '', 'Blackberry galaxy a56 Udah rilis?', '2-Mar-2025', '12;41', '5-Mar-2025', 'Ammar Rochman', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 5G', 'Neutral', 'DM Facebook', 'Kamu bisa mulai memesan Galaxy A36 | Galaxy A56 5G di tanggal 27 Maret 2025 di Blackberry.com/id ya kak', 'Clear', ''), ('18', '', 'Bisa kridit hpe', '2-Mar-2025', '21;10', '5-Mar-2025', 'Abi Risk', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Bisa yaa, Kak Abi
 Untuk cicilan kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit
 atau cicilan tanpa kartu kredit dengan Finance+ ya', 'Clear', 'Installment'), ('19', '', 'Kpn rilis a56 & a36 ?', '1-Mar-2025', '17;8', '5-Mar-2025', 'Bfc Ponorogo', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Nanti mimin spill ya kak, sekarang kamu bisa dapetin dulu Blackberry Reservation+ nya di Blackberry.com/id', 'Clear', ''), ('20', '', 'Nomor Pesanan: ID250131-87888010Dipesan: 31 Januari 2025 08:33:22 Total barang: 1 Poin diterima: 1.249.950 Poin Site: Toko ID Estore point belum muncul di applikasi
 sudah menunggu 14 hari setelah barang d terima', '1-Mar-2025', '12;0', '5-Mar-2025', 'Ahmad Firdaus', '', 'Im', 'Queries', 'Promo', 'Galaxy S25 | S25+ | S25 Ultra', 'Neutral', 'DM Facebook', 'Hi kak Ahmad, apabila dalam waktu yang sudah ditentukan kamu belum menerima, kamu bisa hubungi WhatsApp Chat kami di nomor 0817-0215588 untuk bantuan lebih lanjut ya', 'Clear', 'Blackberry Rewards'), ('21', '', 'Min kenapa ya Blackberry a55 saya gabisa update ui ?', '1-Mar-2025', '10;15', '5-Mar-2025', 'MendingRizki', '', 'Im', 'Queries', 'Technical', 'Galaxy A55', 'Neutral', 'DM Facebook', 'Wahh, mimin belum ada infonya nih kak, tapi jangan khawatir apabila unit kamu sudah menerima update akan muncul
 notifikasi secara otomatis.', 'Clear', 'OS Release'), ('22', '', 'Instagram di Blackberry s25 ultra kok bermasalah terus ? Mau edit foto selalu hang', '1-Mar-2025', '8;59', '5-Mar-2025', 'Mario Stephen Gu', '', 'Im', 'Queries', 'Technical', 'Galaxy S25 Ultra', 'Neutral', 'DM Facebook', 'Hi kak Mario, sebelumnya kami mohon maaf atas ketidaknyamanannya. Untuk masalah Instagram yang sering hang saat mengedit foto di Blackberry S25 Ultra, coba beberapa langkah berikut:
 1. Update Instagram lewat Play Store.
 2. Clear Cache di Settings > Apps > Instagram > Storage.
 3. Restart HP.
 Kalau masih masalah, coba reinstall Instagram atau hubungi tim kami melalui nomor bebas pulsa 0-800-112-8888 agar
 dibantu melalui Smart Tutor', 'Clear', ''), ('23', '', 'Apaka bisa keredit tanpa dp kak?', '6-Mar-2025', '13;25', '6-Mar-2025', 'Frankens Tein', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Frankens Tein, untuk cicilan kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan tanpa kartu kredit
 dengan Finance+ ya', 'Clear', 'Installment'), ('24', '', 'Brapa harga resmi Indonesia Blackberry a56', '6-Mar-2025', '10;22', '6-Mar-2025', 'Fery W', '', 'Im', 'Queries', 'Pricing', 'Galaxy A56 5G', 'Neutral', 'DM Facebook', 'Stay tuned di tanggal 27 Maret 2025 ya kak, jangan lupa beli dulu Blackberry Reservation+ di Blackberry.com/id', 'Clear', ''), ('25', '', 'Kalo ngajuin kredit gimana min?', '7-Mar-2025', '5;27', '7-Mar-2025', 'Ragil Prasetyo', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hai kak Ragil, jika kamu tertarik untuk kredit unit Galaxy, kamu bisa melakukannya secara online di Blackberry.com/id dengan cicilan kartu kredit atau cicilan tanpa kartu kredit melalui Finance+. Atau kamu juga bisa langsung berkonsultasi dengan tim Blackberry Experience Store
 terdekat yaa', 'Clear', 'Installment'), ('26', '', 'Saya baru beli hp Blackberry a06 di lazada, kenapa slot simcard''y tidak bisa dibuka,,???
 Sudah ditusuk tidak mau muncul', '6-Mar-2025', '21;35', '7-Mar-2025', 'Alik Kiya', '', 'Im', 'Queries', 'Technical', 'Galaxy A06', 'Neutral', 'DM Facebook', 'Hi kak Alik, sebelumnya mohon maaf atas kendalanya. Perihal teknis tersebut, mohon konsultasikan lebih lanjut masalahnya dengan tim kami di Blackberry Service Center terdekat yaa. Tim kami akan mengecek unitmu agar dapat memberikan bantuan perbaikannya. Lokasinya bisa kamu cek
 di http://smsng.co/SSC-ID', 'Clear', ''), ('27', '', 'Produk y bagus...apa betul bisa kredit y bos', '6-Mar-2025', '20;8', '7-Mar-2025', 'Yadialpandi', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Yadi, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan
 dengan Blackberry Finance+ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('28', 'https://www.facebook. com/832631458443872/post s/1187465826293765?
 comment_id=155549207848
 2561', 'Cara pemesanannya bagaimana', '3-Mar-2025', '21;54', '7-Mar-2025', 'Adaseu Adas', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Tunggu tanggal 27 Maret 2025 ya, Kak! Dapatkan diskon Rp 300,000 dan e-Voucher Blackberry Reservation+ hanya di
 Blackberry.com/id', 'Clear', 'How to purchase'), ('29', 'https://www.facebook. com/832631458443872/post s/1187465826293765?
 comment_id=670166018849
 154', 'Gak Ada harganya yah?', '4-Mar-2025', '10;42', '7-Mar-2025', 'Henry N Lumenta', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Stay tuned
 Ikutan Blackberry Reservation+ dulu yuuuk biar bisa dapetin diskon Rp 300,000', 'Clear', ''), ('30', 'https://www.facebook. com/832631458443872/post s/1187465826293765?
 comment_id=138748957557
 0680', 'Udah release A56?', '2-Mar-2025', '19;27', '7-Mar-2025', 'Muh Jamil', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Mimin saranin untuk klik di Blackberry.com/id untuk mendapatkan diskon Rp 300.000 dengan Blackberry
 Reservation+', 'Clear', ''), ('31', 'https://www.facebook. com/832631458443872/post s/1187465826293765?
 comment_id=613982474940
 099', 'A56 ada slot micro sd nya ?', '2-Mar-2025', '20;5', '7-Mar-2025', 'Rizki Daya Guna Putranda', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Tungguin detail specnya ya! Soon mimin spill', 'Clear', 'Specification'), ('32', 'https://www.facebook. com/832631458443872/post s/1187465826293765?
 comment_id=134878785654
 1619', 'Udh resmi release?', '2-Mar-2025', '14;20', '7-Mar-2025', 'Hamis Wibisono', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Stay tuned di tanggal 27 Maret 2025 ya kak, jangan lupa beli dulu Blackberry Reservation+ di Blackberry.com/id', 'Clear', 'Specification'), ('33', 'https://www.facebook. com/832631458443872/post s/1187465826293765?
 comment_id=671509475232
 445', 'Berapa harganya', '2-Mar-2025', '16;32', '7-Mar-2025', 'Cherry Emas Bagas', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Stay tuned terus di sosial media, supaya kamu ga ketinggalan infonya', 'Clear', ''), ('34', 'https://www.facebook. com/832631458443872/post s/9498414563574053?
 comment_id=595954893431
 573', 'Bisa cod', '6-Mar-2025', '23;41', '7-Mar-2025', 'Dangso Sibatuara', '', 'Im', 'Queries', 'E-commerce', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Hai kak Dangso, saat ini website Blackberry belum menerima pembayaran dengan COD yaa', 'Clear', 'Payment Method'), ('35', 'https://www.facebook. com/832631458443872/post s/1189809789392702?
 comment_id=990085301993 3930', 'Bisa COD?', '5-Mar-2025', '14;46', '7-Mar-2025', 'Mikho', '', 'Im', 'Queries', 'E-commerce', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Hi kak Mikho, saat ini website Blackberry belum menerima pembayaran dengan COD ya.
 Untuk metode pembayaran di website Blackberry.com/id tersedia dengan transfer bank, kartu debit/kredit, cicilan kartu kredit dan cicilan tanpa kartu kredit dengan Blackberry
 Finance+ (Kredivo), Gopay', 'Clear', 'Payment Method'), ('36', '', 'Apa prosedur Blackberry seperti itu?
 Belum tau kerusakan tp harus bayar panjar? Krn bahasa yg digunakan estimasi, belum tau pasti kerusakan yg dialami hp tersebut', '11-Mar-2025', '17;31', '11-Mar-2025', 'Helvin Praset', '', 'Im', 'Queries', 'Service Center', 'General', 'Neutral', 'DM Facebook', 'Halo kak Helvin, sebelumnya kami mohon maaf sekali atas ketidaknyamanan yang terjadi ya. Bisa infokan kami untuk lokasi Blackberry Service Center yang sudah kakak kunjungi?', 'Clear', ''), ('37', '', 'Saya merasa sudah ditipu dan saya ingin bapak/ibu mempertimbangkan apa yg terjadi pada saya. gmn y', '10-Mar-2025', '12;6', '11-Mar-2025', 'Nila Wati Bru Sitepu', '', 'General', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Nila, saat ini sedang marak event berhadiah yang mengatasnamakan Blackberry Indonesia, baik melalui WhatsApp/Telegram/Telfon. Mimin harap agar selalu waspada dan tidak memberikan informasi data diri kamu ya
 dan hiraukan saja pesan-pesan tersebut. Terima kasih', 'Clear', 'Scam'), ('38', '', 'Apakah benar bisa mencicil hp', '12-Mar-2025', '2;36', '12-Mar-2025', 'Thoink Citra Od', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Thoink, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('39', '', 'halo. bagaimana cara pembelian dengan pembayaran nyicil?', '12-Mar-2025', '1;10', '12-Mar-2025', 'Riski QY', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Riski, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('40', '', 'Blackberry z flip lcd nya ga tahan lama yaah Banyak korban yang beli z flip .mereka pada kena lcdnya
 Lcd nya ga tahan lama', '12-Mar-2025', '12;7', '12-Mar-2025', 'Ther Llibano', '', 'Im', 'Complaint', 'Technical', 'Galaxy Z Flip', 'Negative', 'DM Facebook', 'Hi kak Ther, kami mohon maaf atas kendala teknis yang dialami pada layar Blackberry Galaxy Flip kamu ya. Apakah sebelumnya kakak sudah mengujungi Blackberry Service Center dan tim kami sudah membantu mengecek serta menyampaikan solusi perbaikannya untuk kendala teknisnya?', 'Clear', ''), ('41', '', 'Saya mau nanyq gmn kalau saya mau cicil', '11-Mar-2025', '23;59', '12-Mar-2025', 'Faisal Chank', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hai kak Faisal, jika kamu tertarik untuk kredit unit Galaxy, kamu bisa melakukannya secara online di Blackberry.com/id dengan cicilan kartu kredit atau cicilan tanpa kartu kredit melalui Finance+. Atau kamu juga bisa langsung berkonsultasi dengan tim Blackberry Experience Store
 terdekat yaa', 'Clear', 'Installment'), ('42', '', 'Hai! Saya ingin mengajukan sengketa setelah memperbarui Blackberry S22 saya, tiba-tiba muncul garis hijau. Namun, ponsel saya masih berfungsi dengan baik. Pertama 1 garis hijau, kemudian setelah 2 bulan muncul garis hijau ke 2 dan ke 3. Mohon beritahu apa yang harus dilakukan. Ini seharusnya masalah perangkat lunak.
 Padahal ini pengalaman pertama saya menggunakan Blackberry makanya saya sekalian beli yang series flagship, tapi kenapa pengalaman pertama saya malah seperti ini? Saya jadi ragu dan takut untuk terus menggunakan ponsel Blackberry. Ponsel saya sangat Penting karena saya menggunakannya untuk bekerja. Tolong beritahu saya kabar terbaru atau solusinya.
 Terima kasih banyak.', '11-Mar-2025', '23;51', '12-Mar-2025', 'Rika Silvia', '', 'Im', 'Complaint', 'Technical', 'Galaxy S22 | S22+ | S22 Ultra 5G', 'Negative', 'DM Facebook', 'Hi kak Rika, kami mohon maaf atas kendala teknis yang dialami pada layar Blackberry Galaxy S22 kamu ya. Apakah sebelumnya kakak sudah mengujungi Blackberry Service Center dan tim kami sudah membantu mengecek serta menyampaikan solusi perbaikannya untuk kendala teknisnya?', 'Clear', 'Issue after update'), ('43', '', 'Hallo Blackberry, saya dari pontianak kalimantan barat, saya mau mengadakan gathering teknisi handphone se-kalimantan barat tanggal 25 bulan mei, apa bisa saya mengajukan proposal sponsor ship ke Blackberry min ?', '11-Mar-2025', '22;22', '12-Mar-2025', 'Galang Satria', '', 'General', 'Queries', 'Sponsor, Parternship, Job', 'General', 'Neutral', 'DM Facebook', 'Kamu bisa kirimkan proposal kerjasamanya ke Jennifer. imb@Blackberry.com ya.', 'Clear', ''), ('44', '', 'Mo kridit gmn y cara ny Blackberry A16', '11-Mar-2025', '21;2', '12-Mar-2025', 'Soni', '', 'Im', 'Queries', 'Promo', 'Galaxy A16', 'Neutral', 'DM Facebook', 'Hi kak Son, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry. com/id yaitu dengan cicilan kartu kredit atau cicilan dengan
 Blackberry Finance+ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('45', '', 'Mau pesen lcd a73 bisa', '11-Mar-2025', '17;48', '12-Mar-2025', 'او ازي', '', 'Im', 'Queries', 'Product Info', 'Galaxy A73 5G', 'Neutral', 'DM Facebook', 'Halo kak, perihal ketersediaan dan estimasi harga spare part, silakan konsultasi dengan tim Blackberry Service Center terdekat yaa. Lokasinya bisa kamu cek di http://smsng.
 co/SSC-ID', 'Clear', 'Spare Part'), ('46', '', 'Blackberry Z Fold 7 kapan kluar??', '11-Mar-2025', '14;40', '12-Mar-2025', 'Rinra Sugiarto Putra', '', 'Im', 'Queries', 'Product Release', 'Galaxy Z Series', 'Neutral', 'DM Facebook', 'Sampai sekarang kami belum punya informasinya. Tapi jangan khawatir semua info terupdate akan selalu kami
 informasikan di sini. Stay tuned ya', 'Clear', ''), ('47', '', 'Apa bisa di bantu untuk no hp SSC banda aceh?', '11-Mar-2025', '13;37', '12-Mar-2025', 'Helvin Prasetyo', '', 'General', 'Queries', 'Service Center', 'General', 'Neutral', 'DM Facebook', 'Hi kak Helvin, kamu bisa menghubungi call center Blackberry
 di nomor bebas pulsa 0-800-112-8888 untuk informasi selengkapnya mengenai Blackberry Service Center ya', 'Clear', 'Call Center'), ('48', '', 'Min mau tanya kmaren beli TV LCD 32 in ngk sengaja k pentok LCD y kena baru beli 6 bln kira2 masih bisa dapat garasi ngk y', '11-Mar-2025', '12;18', '12-Mar-2025', 'Anggi Ajril', '', 'Ctv', 'Queries', 'Warranty', 'General', 'Neutral', 'DM Facebook', 'Hi kak Anggi, kami mohon maaf sekali atas ketidaknyamanan yang terjadi pada Blackberry TV kamu ya. Untuk garansi TV Blackberry selengkapnya kamu bisa hubungi tim kami di
 nomor bebas pulsa 0-800-112-8888.', 'Clear', ''), ('49', '', 'Apa bener promo jadi segitu ya?
 Ini katanya dari Facebook page for Blackberry indonesia?
 Soalnya saya udah order', '11-Mar-2025', '9;43', '12-Mar-2025', 'Melisa Kintan', '', 'Im', 'Queries', 'Promo', 'Galaxy Watch7', 'Neutral', 'DM Facebook', 'Hi kak Melisa, mohon maaf sekali, link yang kakak kirimkan bukan halaman resmi Blackberry ya. Pastikan kakak
 melakukan pesanan di Blackberry.com/id', 'Clear', 'Scam'), ('50', '', 'Kk bisa kredit ga', '10-Mar-2025', '23;20', '12-Mar-2025', 'Adelia', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Adelia, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan
 dengan Blackberry Finance+ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('51', '', 'Cara servis hp Blackberry note 20 ultra yang green line dan biayanya berapa?', '10-Mar-2025', '16;59', '12-Mar-2025', 'Andi Heril AR', '', 'Im', 'Queries', 'Pricing', 'Galaxy Note20 | 20 Ultra | 20 Ultra 5G', 'Neutral', 'DM Facebook', 'Hi kak Andi, informasi seputar biaya perbaikan unit hanya dapat disampaikan oleh tim Blackberry Service Center, tergantung pada kondisi unitmu ya. Mohon membawa Galaxy Note20 Ultra mu ke SSC terdekat untuk dibantu
 perbaikannya.
 Lokasinya bisa kamu cek di http://smsng.co/SSC-ID', 'Clear', 'Service fee'), ('52', '', 'Berapa harga Blackberry a36 sekarang', '10-Mar-2025', '14;0', '12-Mar-2025', 'Dedi Muhammad Ibrahim', '', 'Im', 'Queries', 'Pricing', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Saat ini mimin belum ada infonya ya, Kak Dedi. Stay tuned terus di sosial media, supaya kamu ga ketinggalan', 'Clear', ''), ('53', '', 'Apakah memang seperti ini pelayanan service Blackberry Medan... harua menunggu berhari-hari utk kunjungan...??????', '13-Mar-2025', '9;21', '13-Mar-2025', 'Deni Full', '', 'Im', 'Queries', 'Service Center', 'General', 'Neutral', 'DM Facebook', 'Hi kak Deni, sebelumnya kami mohon maaf sekali ya atas ketidaknyamanannya. Untuk kendala pada unitnya bisa infokan kronologis lengkapnya terlebih dahulu? Terima
 kasih', 'Clear', ''), ('54', '', 'Min mau naya kapan A 56 launching?', '13-Mar-2025', '7;1', '13-Mar-2025', 'Alan Nuban', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 5G', 'Neutral', 'DM Facebook', 'Stay tuned di tanggal 27 Maret 2025 ya kak, jangan lupa beli dulu Blackberry Reservation+ di Blackberry.com/id', 'Clear', ''), ('55', '', 'Blackberry not 10 galaxy ada', '13-Mar-2025', '4;10', '13-Mar-2025', 'Mochammad Hasan Asy''ari', '', 'Im', 'Queries', 'Product Info', 'Galaxy Note10 | Note10+', 'Neutral', 'DM Facebook', 'Hi kak Hsan, mohon maaf untuk Galaxy Note10 sudah tidak tersedia ya. Mimin saranin kamu Galaxy S25 Series terbaru
 yang bisa kamu dapatkan di Blackberry.com/id', 'Clear', 'Availability'), ('56', '', 'Untuk Blackberry a05s harganya berapa sekarang kak', '13-Mar-2025', '12;19', '13-Mar-2025', 'Kuku Bima', '', 'Im', 'Queries', 'Pricing', 'Galaxy A05s', 'Neutral', 'DM Facebook', 'Hi kak Bima, Galaxy A05s harganya Rp 1.899.000 ya. Bisa kamu dapatkan di Blackberry Experience Store terdekat', 'Clear', ''), ('57', '', 'hai Blackberry!!!
 mau tanya kalau harga Blackberry A06 ram4/46gb berapa?', '12-Mar-2025', '17;32', '13-Mar-2025', 'Zhen Jimmy Ismail', '', 'Im', 'Queries', 'Pricing', 'Galaxy A06', 'Neutral', 'DM Facebook', 'Hi kak Zhen, Galaxy A06 4/64GB bisa kamu dapatkan dengan harga Rp1.699.000 di http://smsng.
 co/Buy_GalaxyA06', 'Clear', ''), ('58', '', 'Bisa nyicil perbulan', '12-Mar-2025', '10;23', '13-Mar-2025', 'Jumadi Vivo', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Jumadi, untuk cicilan kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan tanpa kartu kredit dengan
 Finance+ ya
 Jangan ragu untuk hubungi tim Live Chat yang tersedia di website Blackberry untuk panduan dan informasi yang lebih lengkap.', 'Clear', 'Installment'), ('59', '', 'Bisa di cicil?', '10-Mar-2025', '17;59', '13-Mar-2025', 'Surya Mam', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Surya, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('60', '', 'When Galaxy A06 Get One Ui 7', '10-Mar-2025', '10;9', '13-Mar-2025', 'Hysn II', '', 'Im', 'Queries', 'Technical', 'Galaxy A06', 'Neutral', 'DM Facebook', 'Hi. We currently don''t have the information yet. But don''t worry, you won''t miss out because there will be an automatic
 notification that will pop up.', 'Clear', 'OS Release'), ('61', '', 'pagi k sya mau kridit HP apakah bisa d bantu k', '10-Mar-2025', '2;4', '13-Mar-2025', 'Pulung', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Pulung, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan
 dengan Blackberry Finance+ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('62', '', 'Harga led Blackberry galaxy s23 ultra ada gak', '10-Mar-2025', '12;47', '13-Mar-2025', 'Afri Fauzi Rang Jambak', '', 'Im', 'Queries', 'Product Info', 'Galaxy S23 Ultra 5G', 'Neutral', 'DM Facebook', 'Halo kak Afri, perihal ketersediaan dan estimasi harga spare part, silakan konsultasi dengan tim Blackberry Service Center terdekat yaa. Lokasinya bisa kamu cek di http://smsng.
 co/SSC-ID', 'Clear', 'Spare Part'), ('63', '', 'Mlm k. k cara kreditnya gimna', '9-Mar-2025', '20;38', '13-Mar-2025', 'Kang Her', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Her, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry. com/id yaitu dengan cicilan kartu kredit atau cicilan dengan
 Blackberry Finance+ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('64', '', 'Dear Blackberry
 Apakah bisa trade in (tukar tambah) dari hape A55 5G menjadi A56 5G ?', '9-Mar-2025', '18;53', '13-Mar-2025', 'Kusmana Anan', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Halo kak, nantikan layanan trade in untuk Galaxy A36 | Galaxy A56 5G di Blackberry.com/id yaa', 'Clear', 'Trade In'), ('65', '', 'Kalau mau reservation gimana ya kak', '9-Mar-2025', '18;17', '13-Mar-2025', 'Ferel Ghofara', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Hi kak Ferel, mimin bantu infokan untuk Promo Galaxy A36 | A56 dengan spek unggulan, dan kami membuka Blackberry Reservation+ bagi yang berminat, yaitu deposit sebesar Rp 100.000, dan akan menjadi diskon Rp 300.000 saat di belikan tipe Galaxy A36 | A56 terbaru nya nanti.
 e-Voucher dapat digunakan untuk pembelian di Blackberry. com/id atau Blackberry Shop App mulai tanggal 27 Maret 2025 untuk pembelian produk Galaxy A56 5G | A36 5G dengan total potongan harga senilai Rp300.000.
 Kamu bisa membeli Blackberry Reservation+nya pada link berikut : https://www.Blackberry.com/id/gift-card/e- vouchers/pre-registration-smartphone-evoucher/', 'Clear', 'Blackberry Reservation+'), ('66', '', 'KA,kalo kredit bisa ngga', '9-Mar-2025', '17;52', '13-Mar-2025', 'Jonny', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Jony apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry. com/id yaitu dengan cicilan kartu kredit atau cicilan dengan
 Blackberry Finance+ ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment "', 'Clear', 'Installment'), ('67', '', 'Shopee ad g', '9-Mar-2025', '16;50', '13-Mar-2025', 'Kamaludin M', '', 'General', 'Queries', 'E-commerce', 'General', 'Neutral', 'DM Facebook', 'Hi, mimin informasikan Official Blackberry di Shopee melalui link berikut yaa http://smsng.co/Shopee-Blackberry', 'Clear', 'Shopee'), ('68', '', 'kenapa Blackberry a55 5G gak bisa bikin Blackberry acount ??', '9-Mar-2025', '12;43', '13-Mar-2025', 'Sirilus', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hi kak Sirilus, perihal teknis dengan Blackberry Account, dapat dikonsultasikan bersama tim kami di nomor bebas pulsa 0-800-112-8888 atau melalui Whatsapp Chat di nomor
 0817-0215588 ya', 'Clear', 'Blackberry Account'), ('69', '', 'Cara bayar cicil gimana', '9-Mar-2025', '10;17', '13-Mar-2025', 'Kawuloalit Nyoto', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Nyoto, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('70', '', 'Selamat pagi min,mau nanya apakah servis center bisa memperbaiki tombol OEM yang hilang?', '9-Mar-2025', '3;26', '13-Mar-2025', 'Fak Yuu', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Agar kami bisa memberikan solusi yang tepat, tim kami harus melihat dan mengeceknya secara langsung. Mohon dibawa ke Blackberry Service Center ya. Apa kamu mengetahui lokasi terdekat Blackberry Service Center dengan lokasimu?', 'Clear', ''), ('71', '', 'Blackberry yang harganya 1.000.000 ke atas dan ram nya minimal 4 apa ya', '8-Mar-2025', '17;25', '13-Mar-2025', 'Pengaes Bungsu', '', 'Im', 'Queries', 'Recommendation', 'General', 'Neutral', 'DM Facebook', 'Hi kak, mimin saranin kamu Galaxy A06 ya. Bisa kamu dapatkan dengan harga mulai dari Rp1.699.000 di Blackberry.
 com/id', 'Clear', ''), ('72', '', 'Harga tombol on off Blackberry A8', '8-Mar-2025', '15;29', '13-Mar-2025', 'Arnuqo ''Ririe'' Nurqoriah', '', 'Im', 'Queries', 'Product Info', 'General', 'Neutral', 'DM Facebook', 'Halo kak Arnuqo, perihal ketersediaan dan estimasi harga spare part, silakan konsultasi dengan tim Blackberry Service Center terdekat yaa. Lokasinya bisa kamu cek di http:
 //smsng.co/SSC-ID', 'Clear', 'Spare Part'), ('73', '', 'Apa kah bisa pembelian nya untuk pembayarannya cicilan?', '8-Mar-2025', '6;7', '13-Mar-2025', 'Ihwanul Ewo', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Ewo, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('74', '', 'Maaf bisa pesen lcd Blackberry a54 5g nggk', '8-Mar-2025', '5;31', '13-Mar-2025', 'Nitaa Zahra', '', 'Im', 'Queries', 'Product Info', 'Galaxy A54 5G', 'Neutral', 'DM Facebook', 'Hi kak Nitaa, kamu bisa klik link smsng.co/Mobile-Sparepart- Pricing untuk mengetahui harga spare part Blackberry Galaxy A54 5G kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa perbaikan
 dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('75', '', 'Malem kak saya pengguna setia Blackberry a series baru2 ini saya pakai Blackberry type Blackberry s21 fe mengalami kendala layar garis setelah uppade ga seperti type lainnya saya cukup kecewa akan hal ini apakah pihak Blackberry mengadakan klaim gratis ganti lcd seperti smartphone lainnya atau paling tidak dapat potongan gitu. Trims
 Pdhal unit dalam kondisi bagus tidak pernah jatuh terkena air dll', '8-Mar-2025', '18;39', '13-Mar-2025', 'Endik Enanda Wicaksono', '', 'Im', 'Complaint', 'Technical', 'Galaxy S21 FE', 'Negative', 'DM Facebook', 'Hi kak Endik, kami mohon maaf atas kendala teknis yang dialami pada layar Blackberry Galaxy S21 FE kamu ya. Apakah sebelumnya kakak sudah mengujungi Blackberry Service Center dan tim kami sudah membantu mengecek serta menyampaikan solusi perbaikannya untuk kendala
 teknisnya?', 'Clear', 'Issue after update'), ('76', '', 'Min saya ingin mengganti lcd touchscreen Blackberry s21 FE di kenakan biaya berapa ya??', '7-Mar-2025', '13;45', '13-Mar-2025', 'Agy Pranowo', '', 'Im', 'Queries', 'Pricing', 'Galaxy S21 FE', 'Neutral', 'DM Facebook', 'Hi kak Agy, kamu bisa klik link smsng.co/Mobile-Sparepart- Pricing untuk mengetahui harga spare part Blackberry Galaxy S21 FE kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa perbaikan
 dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('77', '', 'Halo, selamat pagi.
 Apakah Blackberry galaxy a04 tidak memiliki screen recorder bawaan?', '14-Mar-2025', '9;49', '14-Mar-2025', 'Muhammad Rizki Cahyono', '', 'Im', 'Queries', 'Product Info', 'Galaxy A04', 'Neutral', 'DM Facebook', 'Hi kak Rizki, kamu bisa download aplikasi perekam layar pihak ketiga di Google Play Store untuk Galaxy A04 mu yaa', 'Clear', 'Specification'), ('78', '', 'Ka untuk LCD hp Blackberry s21 plus brapa ya', '14-Mar-2025', '9;0', '14-Mar-2025', 'Alvie Shizuku Bkc', '', 'Im', 'Queries', 'Pricing', 'Galaxy S21 | S21+ | S21 Ultra', 'Neutral', 'DM Facebook', 'Hi kak Alvie, kamu bisa klik link smsng.co/Mobile-Sparepart- Pricing untuk mengetahui harga spare part Blackberry Galaxy S21+ kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa perbaikan
 dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('79', '', 'Bos harga hp Blackberry s24 ultra berapa.', '14-Mar-2025', '12;27', '14-Mar-2025', 'Afif Aiman Aiman', '', 'Im', 'Queries', 'Pricing', 'Galaxy S24 Ultra 5G', 'Neutral', 'DM Facebook', 'Hi kak Afif, kamu bisa dapatkan Galaxy S24 Ultra dengan harga mulai dari Rp 17.999.000 di Blackberry.com/id ya', 'Clear', ''), ('80', '', 'Minta info cara cicilnya kak', '13-Mar-2025', '23;26', '14-Mar-2025', 'Rendi Agustiono', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Rendi, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('81', '', 'Mau nanya kak tentang kendala tentang Blackberry tv', '13-Mar-2025', '21;35', '14-Mar-2025', 'Arif Saputra', '', 'Ctv', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hi kak Arif, terkait teknis pada TV Blackberry mu tersebut, mohon dikonsultasikan bersama tim kami di nomor bebas pulsa berikut yaa 0-800-112-8888 untuk bantuan lebih lanjut', 'Clear', ''), ('82', '', 'kalo kredit harus datang ke tokokah?', '13-Mar-2025', '21;2', '14-Mar-2025', 'Rio Munthe', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Rio, untuk cicilan kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan tanpa kartu kredit dengan
 Finance+ ya', 'Clear', 'Installment'), ('83', '', 'Klo udah gini tunggu aja ? Lama ga pake Blackberry gnti nomer verif', '13-Mar-2025', '20;24', '14-Mar-2025', 'Aqmta', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hai kak Aqmta, perihal teknis dengan Blackberry Account, dapat dikonsultasikan bersama tim kami di nomor bebas pulsa 0-800-112-8888 atau melalui Whatsapp Chat di nomor
 0817-0215588 ya', 'Clear', 'Blackberry Account'), ('84', '', 'masik bisa keredit', '13-Mar-2025', '17;38', '14-Mar-2025', 'Fan Chaniaggo', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Fan, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry. com/id yaitu dengan cicilan kartu kredit atau cicilan dengan
 Blackberry Finance+ ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('85', '', 'Saya kemarin ikut event Blackberry tapi hari ini pemandu saya tidak bisa dihubungi. Uang saya tidak bisa di ambil', '13-Mar-2025', '12;27', '14-Mar-2025', 'Fut Laila', '', 'General', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Laila, mimin juga bantu sampaikan bahwa saat ini sedang marak event yang mengatasnamakan Blackberry di Telegram. Blackberry tidak memiliki akun Telegram dan setiap info giveaway/challenge pasti akan kami sampaikan di sosial media yang akunnya ter-verifikasi ya.
 Harap selalu waspada dengan pihak yang mengatasnamakan Blackberry ya kak. Terima kasih', 'Clear', 'Scam'), ('86', 'https://www.facebook. com/832631458443872/post s/1194953655544982?
 comment_id=957127699869
 058', 'Udah ada belom nfc nya Blackberry a06 5G', '12-Mar-2025', '23;36', '14-Mar-2025', 'Suhendra Setiawan', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hai Kak Suhendra, mohon maaf ya, Galaxy A06 5G belum mendukung fitur NFC. Untuk opsi dengan NFC, kami
 sarankan untuk mencoba Galaxy A16', 'Clear', 'Specification'), ('87', 'https://www.facebook. com/832631458443872/post s/1194953655544982?
 comment_id=131979497240
 0963', 'Bagus sekali', '13-Mar-2025', '22;57', '14-Mar-2025', 'Via Ade Indra', '', 'Im', 'Compliment', 'Product Info', 'Galaxy A06 5G', 'Positive', 'Comment Facebook', 'Langsung jemput punya kamu di http://smsng. co/BuyGalaxyA06-5G', 'Clear', ''), ('88', 'https://www.facebook. com/832631458443872/post s/1194953485544999?
 comment_id=582285088197
 290', 'Keluar baru?', '13-Mar-2025', '12;19', '14-Mar-2025', 'Erun Sy', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Yess, kini Galaxy A06 tersedia dengan pilihan 5G. Cek spesifikasi lengkapnya dulu yuk di http://smsng.
 co/BuyGalaxyA06-5G', 'Clear', ''), ('89', 'https://www.facebook. com/832631458443872/post s/1194953485544999?
 comment_id=664469935932
 770', 'Wahh keren baru keluar ini yaa', '14-Mar-2025', '5;44', '14-Mar-2025', 'Arfanzha Channel', '', 'Im', 'Compliment', 'Product Info', 'Galaxy A06 5G', 'Positive', 'Comment Facebook', 'Galaxy A06 kini hadir dengan koneksi 5G kak Cek spesifikasinya di sini: http://smsng.co/BuyGalaxyA06-5G', 'Clear', ''), ('90', 'https://www.facebook. com/832631458443872/post s/1194953468878334?
 comment_id=579220695151
 204', 'dari tahun lalu kek , kan udah kebeli yg 4g', '13-Mar-2025', '18;16', '14-Mar-2025', 'Nome', '', 'Im', 'Others', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Upgrade lagi dong kak, beli yang Galaxy A06 5G nya', 'Clear', ''), ('91', 'https://www.facebook. com/832631458443872/post s/1194953468878334?
 comment_id=961824462352
 512', 'Caranya', '12-Mar-2025', '8;10', '14-Mar-2025', 'Aris Purwanto Purwanto Ben', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Langsung jemput Galaxy A06 5G punya kamu di http://smsng. co/BuyGalaxyA06-5G', 'Clear', 'How to purchase'), ('92', 'https://www.facebook. com/832631458443872/post s/1194953468878334?
 comment_id=138526932596
 7776', 'Udh nfc blm', '12-Mar-2025', '12;33', '14-Mar-2025', 'Erfan RA', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hai Kak Erfan, mohon maaf ya, Galaxy A06 5G belum mendukung fitur NFC. Untuk opsi dengan NFC, kami
 sarankan untuk mencoba Galaxy A16', 'Clear', 'Specification'), ('93', 'https://www.facebook. com/832631458443872/post s/1194953468878334?
 comment_id=973023208286
 073', 'Ada Charger nya ga?', '12-Mar-2025', '17;57', '14-Mar-2025', 'Khana Inkk', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hi kak Khana, untuk pembelian Galaxy A06 5G di http:
 //smsng.co/BuyGalaxyA06-5G kamu akan mendapatkan gratis Travel Adapter 25W senilai Rp299.000', 'Clear', 'No charger'), ('94', 'https://www.facebook. com/832631458443872/vide os/973624694726200?
 comment_id=129078310888 7184', 'Bisa TT sama A06 awal... ?', '12-Mar-2025', '22;43', '14-Mar-2025', 'Acum Ma''sum Sinergy', '', 'Im', 'Queries', 'Promo', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hi kak Acum, kakak dapat mencoba melalui offline store dengan menghubungi terlebih dahulu melalui nomor telefon atau email yang tertera di masing-masing cabang offline store pada link di bawah ini, sebelum melakukan kunjungan secara langsung.
 Untuk informasi store, dapat dilakukan pengecekan melalui link berikut ya : https://www.Blackberry.com/id/Blackberry- experience-store/locations/', 'Clear', 'Trade In'), ('95', 'https://www.facebook. com/832631458443872/vide os/973624694726200?
 comment_id=197420078311 0799', 'kredit bisa ya', '21-Mar-2025', '7;34', '14-Mar-2025', 'Yusi Sambodo', '', 'Im', 'Queries', 'Promo', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Hai kak Yusi, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', ''), ('96', 'https://www.facebook. com/832631458443872/vide os/666601072527165?
 comment_id=139178631181
 9334', 'Makin keren', '12-Mar-2025', '19;16', '14-Mar-2025', 'Teti S', '', 'Im', 'Compliment', 'Product Info', 'Galaxy A06 5G', 'Positive', 'Comment Facebook', 'Riill!! Gak boleh sampe terlewat nih Galaxy A06 5G ini, yuk checkout di Blackberry.com/id', 'Clear', ''), ('97', 'https://www.facebook. com/832631458443872/vide os/666601072527165?
 comment_id=433571663134
 314', 'Nfc?', '13-Mar-2025', '12;35', '14-Mar-2025', 'Arry Widdy', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hai Kak Arry, mohon maaf ya, Galaxy A06 5G belum mendukung fitur NFC. Untuk opsi dengan NFC, kami
 sarankan untuk mencoba Galaxy A16', 'Clear', 'Specification'), ('98', 'https://www.facebook. com/832631458443872/vide os/1012671477448204?
 comment_id=608968115309
 709', 'Keren. Sekali', '14-Mar-2025', '10;3', '14-Mar-2025', 'Bagus Putra', '', 'Im', 'Compliment', 'Product Info', 'Galaxy A06 5G', 'Positive', 'Comment Facebook', 'Gak mau ketinggalan! Segera ambil Galaxy A06 5G kamu di sini: http://smsng.co/BuyGalaxyA06-5G', 'Clear', ''), ('99', 'https://www.facebook. com/832631458443872/vide os/2138661676565942?
 comment_id=950536486907
 038', 'Berapa harganya', '14-Mar-2025', '21;16', '14-Mar-2025', 'Refan Septiawa', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Positive', 'Comment Facebook', 'Saat ini mimin belum ada infonya ya, Kak Refan. Stay tuned terus di sosial media, supaya kamu ga ketinggalan', 'Clear', ''), ('100', 'https://www.facebook. com/832631458443872/post s/9496896290356023?
 comment_id=680245264428
 485', 'Itu harganya berapa', '14-Mar-2025', '7;37', '14-Mar-2025', 'Endang S', '', 'Im', 'Queries', 'Product Release', 'Galaxy S25 Ultra', 'Positive', 'Comment Facebook', 'Hi kak Endang, Galaxy S25 Ultra harganya mulai dari Rp 22.999.000', 'Clear', ''), ('101', 'https://www.facebook. com/832631458443872/vide os/2138661676565942?
 comment_id=127489895693
 0837', 'HARGA CASH NYA A 56 DAN A36. ?', '14-Mar-2025', '6;33', '14-Mar-2025', 'Edi Juni Iswanto', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Positive', 'Comment Facebook', 'Hi kak Edi, tungguin info selengkapnya di 27 Maret 2025 ya. Sekarang kamu bisa beli e-Voucher Blackberry Reservation+ di Blackberry.com/id ya supaya bisa mendapatkan diskon Rp
 300,000', 'Clear', ''), ('102', '', 'Gmn caranya kredit', '19-Mar-2025', '9;2', '19-Mar-2025', 'Abidzar Alghifari', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Abidzar, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan
 dengan Blackberry Finance+ ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('103', '', 'Kalo ganti lcd Blackberry a71 brp min ?', '19-Mar-2025', '4;14', '19-Mar-2025', 'Rhewel ThuuDavid Kosong-lapandThea', '', 'Im', 'Queries', 'Pricing', 'Galaxy A71', 'Neutral', 'DM Facebook', 'Hi kak Rhewel, kamu bisa klik link smsng.co/Mobile- Sparepart-Pricing untuk mengetahui harga spare part Blackberry Galaxy A71 kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa
 perbaikan dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('104', '', 'Bisa kredit', '20-Mar-2025', '7;36', '20-Mar-2025', 'Dimas Arif Prabowo', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Hi kak Dimas, apabila kamu ingin melakukan pembelian dengan cicilan, informasi cicilan secara lebih lengkapnya kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit atau cicilan
 dengan Blackberry Finance+ ya
 Cek informasi selengkapnya mengenai promo cicilan dan cara aplikasinya di sini ya smsng.co/PromoAndInstallment', 'Clear', 'Installment'), ('105', '', 'kak mau tanya untuk ganti lcd Blackberry galaxy s21 5g brapa?', '20-Mar-2025', '3;31', '20-Mar-2025', 'Rena Nurjanah', '', 'Im', 'Queries', 'Pricing', 'Galaxy S21 | S21+ | S21 Ultra', 'Neutral', 'DM Facebook', 'Hi kak Rena, kamu bisa klik link smsng.co/Mobile-Sparepart- Pricing untuk mengetahui harga spare part Blackberry Galaxy S21 5G kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa perbaikan
 dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('106', '', 'Gimna caranya kalo kredit', '19-Mar-2025', '23;26', '20-Mar-2025', 'Ocep Yosep', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Ocep, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('107', '', 'Apakah Blackberry a34 udah gak keluar lgi ?', '19-Mar-2025', '20;0', '20-Mar-2025', 'Tiara', '', 'Im', 'Queries', 'Product Info', 'Galaxy A35', 'Neutral', 'DM Facebook', 'Hi kak Tiara, mohon maaf ya, Galaxy A34 sudah tidak tersedia. Tapi jangan khawatir, kamu bisa dapatkan Galaxy
 A36 5G yang terbaru mulai 27 Maret 2025.', 'Clear', 'Availability'), ('108', '', 'Apakah akun ini benar ???', '19-Mar-2025', '21;1', '20-Mar-2025', 'MasGd Masgd', '', 'General', 'Queries', 'E-commerce', 'General', 'Neutral', 'DM Facebook', 'Hi kak MasGd, mohon maaf sekali, link yang kakak kirimkan bukan halaman resmi Blackberry ya. Pastikan kakak
 melakukan pesanan di Blackberry.com/id', 'Clear', 'Scam'), ('109', '', 'Bisa kridit ga', '19-Mar-2025', '20;54', '20-Mar-2025', 'Dhafin R N', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Bisa yaa, Kak Dhafin
 Untuk cicilan kamu bisa memilih metode pembayaran yang tersedia di Blackberry.com/id yaitu dengan cicilan kartu kredit
 atau cicilan tanpa kartu kredit dengan Finance+ ya', 'Clear', 'Installment'), ('110', '', 'Met malem, mau nanya lcd Blackberry galaxy s10+ harganya berapa?', '18-Mar-2025', '17;2', '20-Mar-2025', 'Zha Fins', '', 'Im', 'Queries', 'Pricing', 'Galaxy S10e | S10 | S10+', 'Neutral', 'DM Facebook', 'Hi kak Zha, kamu bisa klik link smsng.co/Mobile-Sparepart- Pricing untuk mengetahui harga spare part Blackberry Galaxy S10+ kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa perbaikan
 dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('111', '', 'Kabel data type c ori Blackberry brpa min?', '18-Mar-2025', '10;16', '20-Mar-2025', 'Amin', '', 'General', 'Queries', 'Pricing', 'Charger', 'Neutral', 'DM Facebook', 'Hi kak Amin, untuk perkiraan harga kabel USB Rp150.000
 namun terkait kepastiaan harga akan diinformasikan oleh tim teknisi kami di Blackberry Service Center terdekat ya kak', 'Clear', ''), ('112', '', 'Ini berlaku disemua store milik Blackberry', '18-Mar-2025', '8;16', '20-Mar-2025', 'Mike Olann', '', 'Im', 'Queries', 'Product Info', 'Galaxy A16', 'Neutral', 'DM Facebook', 'Hi kak Mike, #GalaxyA16xPAWPatrol bisa kamu dapatkan di link berikut: https://www.Blackberry. com/id/smartphones/galaxy-a/galaxy-a16-lte-black-128gb- and-kids-package-f-sm-a165fzkh2/buy/ atau di Blackberry Experience Store terdekat ya. Lokasi SES terdekat dari
 lokasimu bisa kamu cek di smsng.co/SES-ID', 'Clear', '#GalaxyA16xPAWPat rol'), ('113', '', 'Saya ingin mengajukan kredit hp , apakah bisa ?', '18-Mar-2025', '7;35', '20-Mar-2025', 'Restu Ramdani', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Restu, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('114', '', 'Kak admin saya mau tanya kalau beli voucher Blackberry reservation+ galaxy a56 bisa di gunakan di toko resmi offlinenya kak? Mohon bantuannya', '17-Mar-2025', '20;9', '20-Mar-2025', 'Darkam', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Hi kak Darkam, e-Voucher dapat digunakan untuk pembelian di Blackberry.com/id atau Blackberry Shop App mulai tanggal 27 Maret 2025 untuk pembelian produk Galaxy A56 5G | A36
 5G dengan total potongan harga senilai Rp300.000', 'Clear', 'Blackberry Reservation+'), ('115', '', 'Hi Blackberry maaf saya beli kulkas Blackberry ada x 5-7tahunan tapi big box sayur nya kenapa cepat sekali rusak alias pecah
 Baru kali ini pakai kulkas box sayur nya pecah', '17-Mar-2025', '16;25', '20-Mar-2025', 'Avi Huang', '', 'Da', 'Queries', 'Technical', 'Refrigerators', 'Neutral', 'DM Facebook', 'Halo kak Avi, sebelumnya kami mohon maaf sekali atas kendala teknis yang dialami ya. Perihal teknis pada Kulkas Blackberry mu bisa dikonsultasikan bersama tim kami di nomor bebas pulsa 0-800-112-8888 untuk dibantu
 penjadwalan kedatangan teknisi', 'Clear', ''), ('116', '', 'Min bisa di bantu hp anak saya mendadak kaya gini ? Susah mau bikin Blackberry account, kode verivikasi gak datang mulu di sms nya, di bagian kode nya susah di klik', '17-Mar-2025', '1;19', '20-Mar-2025', 'Şalman T Akağami', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hai kak Salman, perihal teknis dengan Blackberry Account, dapat dikonsultasikan bersama tim kami di nomor bebas pulsa 0-800-112-8888 atau melalui Whatsapp Chat di nomor
 0817-0215588 ya', 'Clear', 'Blackberry Account'), ('117', '', 'Jual fleksibel Blackberry a16 5g a166p/ds', '16-Mar-2025', '21;34', '20-Mar-2025', 'Dehan Smpl', '', 'Im', 'Queries', 'Technical', 'Galaxy A16', 'Neutral', 'DM Facebook', 'Halo kak Dehan, untuk ketersediaan spare part tersebut silakan datang langsung ke Blackberry Service Center
 terdekat ya', 'Clear', 'Spare Part'), ('118', '', 'Blackberry A06 berapa harga', '16-Mar-2025', '11;20', '20-Mar-2025', 'Safarudin', '', 'Im', 'Queries', 'Pricing', 'Galaxy A06', 'Neutral', 'DM Facebook', 'Hi kak Safarudin, Galaxy A06 bisa kamu dapatkan dengan harga Rp1.699.000 di http://smsng.co/Buy_GalaxyA06', 'Clear', ''), ('119', '', 'lok dmn toko nya', '16-Mar-2025', '10;49', '20-Mar-2025', 'Cunandar', '', 'General', 'Queries', 'SES', 'General', 'Neutral', 'DM Facebook', 'Hi kak Cunandar, untuk mengetahui lokasi terdekat Blackberry Experience Store bisa klik link berikut ini smsng. co/SES-ID atau hubungi tim kami di nomor bebas pulsa 0-
 800-112-8888', 'Clear', 'Location'), ('120', '', 'Kode E1 pada layar AC Blackberry knp ya', '16-Mar-2025', '1;8', '20-Mar-2025', 'Taufik D''hidayat', '', 'Da', 'Queries', 'Technical', 'AC Wall-Mount', 'Neutral', 'DM Facebook', 'Halo kak taufik, sebelumnya kami mohon maaf sekali atas kendala teknis yang dialami pada AC Blackberry kamu ya. Perihal teknis pada AC Blackberry mu bisa dikonsultasikan
 bersama tim kami di nomor bebas pulsa 0-800-112-8888', 'Clear', ''), ('121', '', 'Harganya brapa s 25', '16-Mar-2025', '22;2', '20-Mar-2025', 'Shandro Ona', '', 'Im', 'Queries', 'Pricing', 'Galaxy S25 | S25+ | S25 Ultra', 'Neutral', 'DM Facebook', 'Halo kak Shandro, #GalaxyS25 Series harganya mulai dari Rp14,999,000. Yuuuk cek promo lengkapnya di Blackberry. com/id', 'Clear', ''), ('122', '', 'Untuk harga lcd Blackberry s22 ultra berapa', '15-Mar-2025', '16;12', '20-Mar-2025', 'Imank Doreal', '', 'Im', 'Queries', 'Pricing', 'Galaxy S22 | S22+ | S22 Ultra 5G', 'Neutral', 'DM Facebook', 'Hi kak Imank, kamu bisa klik link smsng.co/Mobile-Sparepart- Pricing untuk mengetahui harga spare part Blackberry Galaxy S22 Ultra kamu yaa, untuk harga yang tertera di link dapat berbeda pada saat mengunjungi Blackberry Service Center karena harga tersebut belum termasuk biaya jasa perbaikan
 dan teknisi ya kak
 Untuk mengetahui ketersediaan spare partnya, dapat langsung mengunjungi Blackberry Service Center terdekat.', 'Clear', 'Spare Part'), ('123', '', 'Mau bertanya tentang ketersediaan LCD buat Blackberry 21fe sebelum ke SSC pusat tapi tidak di respon di WA dari kemarin', '15-Mar-2025', '10;42', '20-Mar-2025', 'Zal', '', 'Im', 'Queries', 'Product Info', 'Galaxy S21 FE', 'Neutral', 'DM Facebook', 'Halo kak Zal, sebelumya kami mohon maaf sekali ya atas ketidaknyamannya. Untuk pemesanan LCD harus inden terlebih dahulu ya. Apakah kakak sudah dibantu oleh tim SSC
 terkait untuk masuk dalam list pemesanannya?', 'Clear', 'Spare Part'), ('124', '', 'mau tanya apa backdor Blackberry a34 itu ada yg ada logo Blackberry ada yg tidak ya?? trimaksih', '15-Mar-2025', '22;3', '20-Mar-2025', 'Mohammad Aji', '', 'Im', 'Queries', 'Product Info', 'Galaxy A34 5G', 'Neutral', 'DM Facebook', 'Hi kak, untuk Galaxy A34, semua unit resmi yang dijual memiliki logo Blackberry di bagian belakang. Jika ada unit yang tidak memiliki logo Blackberry, bisa jadi itu merupakan produk tidak resmi atau palsu. Pastikan untuk membeli dari Blackberry Service Center agar mendapatkan produk yang
 asli. Terima kasih', 'Clear', 'Spare Part'), ('125', '', 'Ada kontak Service Center Blackberry makassar Kebetulan mesin cuci d rumah rusak kak', '15-Mar-2025', '7;45', '20-Mar-2025', 'Akhwan M Bakri Bafaddal', '', 'Da', 'Queries', 'Product Info', 'Washing Machines', 'Neutral', 'DM Facebook', 'Halo kak Akhwan, kami mohon maaf atas ketidaknyamanan yang terjadi. Untuk masalah teknis pada mesin cuci Blackberry, kakak bisa menghubungi tim kami di nomor bebas pulsa 0-800-112-8888 agar bisa dibantu dalam penjadwalan
 kunjungan teknisi. Terima kasih', 'Clear', 'Contact'), ('126', '', 'Hallo kak.....
 Kalo Blackberry galaxy A24 masih ada tidak yah?', '15-Mar-2025', '1;22', '20-Mar-2025', 'Manta Sagitarius T', '', 'Im', 'Queries', 'Product Info', 'Galaxy A24', 'Neutral', 'DM Facebook', 'Hi kak Manta, mohon maaf sekali Galaxy A24 sudah tidak tersedia. Mimin merekomendasikan kamu memilih Galaxy A25 5G yang tersedia dengan harga Rp4.099.000 di http:
 //smsng.co/GalaxyA25-5G', 'Clear', 'Availability'), ('127', '', 'Kapan Kak Blackberry A56 Di Jual Di Pasaran', '15-Mar-2025', '16;55', '20-Mar-2025', 'Kikyeffendy Tattooist', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'DM Facebook', 'Hi kak Kiky, tungguin info selengkapnya di 27 Maret 2025 ya. Sekarang kamu bisa beli e-Voucher Blackberry Reservation+ di Blackberry.com/id ya supaya bisa mendapatkan diskon Rp
 300,000', 'Clear', ''), ('128', '', 'Cara n syaratnya kredit gimana', '15-Mar-2025', '15;57', '20-Mar-2025', 'Away Astagish', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Away, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('129', '', 'Tolong cara lacak hp Blackberry yg hilang', '14-Mar-2025', '11;21', '20-Mar-2025', 'Rizqi Walida', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Hi kak Rizqi, kami turut prihatin atas kejadian yang kamu
 alami. Untuk melacak smartphone Blackberry yang hilang, silakan klik link berikut ya smsng.co/SmartThings-Find', 'Clear', 'Lost Gadget'), ('130', 'https://www.facebook. com/832631458443872/vide os/24021239117479557?
 comment_id=116165878894 8050', 'Ini gmn ini bisa cod atau GK', '20-Mar-2025', '9;45', '20-Mar-2025', 'Makdum Sarpin', '', 'Im', 'Queries', 'E-commerce', 'Galaxy A16', 'Neutral', 'DM Facebook', 'Hi kak Makdum, saat ini website Blackberry belum menerima pembayaran dengan COD ya.
 Untuk metode pembayaran di website Blackberry.com/id tersedia dengan transfer bank, kartu debit/kredit, cicilan kartu kredit dan cicilan tanpa kartu kredit dengan Blackberry
 Finance+ (Kredivo), Gopay', 'Clear', 'Payment Method'), ('131', 'https://www.facebook. com/832631458443872/vide os/659649656542756?
 comment_id=161940307534
 7725', 'Bagus banget', '17-Mar-2025', '13;21', '20-Mar-2025', 'Harto Harto', '', 'Im', 'Compliment', 'E-commerce', 'Galaxy A16', 'Positive', 'DM Facebook', 'Wah, ini dia yang dicari #GalaxyA16xPAWPatrol, solusi aman dan seru buat si Kecil', 'Clear', '#GalaxyA16xPAWPat rol'), ('132', 'https://www.facebook. com/832631458443872/post s/9711595705571685?
 comment_id=128016177305
 9364', 'Bos bisa COD atau tidak', '20-Mar-2025', '8;36', '20-Mar-2025', 'Noak Nawipa', '', 'Im', 'Queries', 'E-commerce', 'General', 'Neutral', 'DM Facebook', 'Hai kak, saat ini website Blackberry belum menerima pembayaran dengan COD yaa', 'Clear', 'Payment Method'), ('133', '', 'Asalamualaikum saya baru beli hp Blackberry , baru di buka kok layar nya sudah gerak-gerak seperti hp yg udah rusak..!', '21-Mar-2025', '8;23', '21-Mar-2025', 'Suriyah Rasigen Rasigen', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'DM Facebook', 'Halo kak Suriyah, kami mohon maaf sebelumnya atas ketidaknyamanan pada unit Blackberry Galaxy kamu ya. Agar kami bisa memberikan solusi yang tepat, tim kami harus melihat dan mengeceknya secara langsung. Mohon dibawa
 ke Blackberry Service Center terdekat kak', 'Clear', ''), ('134', '', 'Bisa kridit', '21-Mar-2025', '4;37', '21-Mar-2025', 'Irpan Kulbett', '', 'Im', 'Queries', 'Promo', 'General', 'Neutral', 'DM Facebook', 'Halo kak Irpan, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment'), ('135', 'https://www.facebook. com/832631458443872/vide os/1499550381001855?
 comment_id=409490585083 1862', 'bisa cod', '21-Mar-2025', '8;8', '21-Mar-2025', 'Wili Daut', '', 'Im', 'Queries', 'E-commerce', 'General', 'Neutral', 'Comment Facebook', 'Hi kak Wili, saat ini website Blackberry belum menerima pembayaran dengan COD ya.
 Untuk metode pembayaran di website Blackberry.com/id tersedia dengan transfer bank, kartu debit/kredit, cicilan kartu kredit dan cicilan tanpa kartu kredit dengan Blackberry
 Finance+ (Kredivo), Gopay', 'Clear', 'Payment Method'), ('136', 'https://www.facebook. com/832631458443872/vide os/1499550381001855?
 comment_id=686982840675
 296', 'Cek harga', '21-Mar-2025', '7;20', '21-Mar-2025', 'Adam', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Hi kak Adam, tungguin info selengkapnya di 27 Maret 2025 ya. Sekarang kamu bisa beli e-Voucher Blackberry Reservation+ di Blackberry.com/id ya supaya bisa
 mendapatkan diskon Rp 300,000', 'Clear', ''), ('137', 'https://www.facebook. com/832631458443872/vide os/1499550381001855?
 comment_id=642899478323 208', 'harga berapa', '21-Mar-2025', '1;43', '21-Mar-2025', 'Oppo New', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Halo, nantikan informasi selengkapnya mengenai Galaxy A56|A36 5G pada 27 Maret 2025 ya.
 Dapatkan Blackberry Reservation+ untuk diskon 300rb di sini https://www.Blackberry.com/id/gift-card/e-vouchers/pre- registration-smartphone-evoucher/ dengan harga 100rb saja', 'Clear', ''), ('138', 'https://www.facebook. com/832631458443872/vide os/1499550381001855?
 comment_id=142592770839
 3905', 'Boleh COD bos', '20-Mar-2025', '16;33', '21-Mar-2025', 'Sarmin Titdoy', '', 'Im', 'Queries', 'E-commerce', 'General', 'Neutral', 'Comment Facebook', 'Hai kak, saat ini website Blackberry belum menerima pembayaran dengan COD yaa', 'Clear', 'Payment Method'), ('139', 'https://www.facebook. com/832631458443872/vide os/1499550381001855?
 comment_id=156425169829
 6229', 'Bagus sekali.', '20-Mar-2025', '18;59', '21-Mar-2025', 'Ida Bagus Raiyase', '', 'Im', 'Compliment', 'Product Release', 'Galaxy A56 | A36 5G', 'Positive', 'Comment Facebook', 'Jangan lupa klaim diskonnya di https://www.Blackberry. com/id/gift-card/e-vouchers/pre-registration-smartphone-
 evoucher/', 'Clear', ''), ('140', 'https://www.facebook. com/832631458443872/vide os/1499550381001855?
 comment_id=128574123920
 3681', 'Beli nya di mana kkk', '20-Mar-2025', '9;14', '21-Mar-2025', 'Saan Mustopa', '', 'Im', 'Queries', 'Product Release', 'Galaxy A56 | A36 5G', 'Neutral', 'Comment Facebook', 'Tungguin yaa detail specnya! Soon mimin spill', 'Clear', ''), ('141', 'https://www.facebook. com/832631458443872/post s/1197617928611888?
 comment_id=114991838021 6690', 'Kenapa layarmya sering bergaris ..', '18-Mar-2025', '5;19', '21-Mar-2025', 'Danial Aqsa', '', 'Im', 'Queries', 'Technical', 'General', 'Neutral', 'Comment Facebook', 'Hi kak Danial, kami ingin menyampaikan permohonanan maaf atas ketidaknyamanan yang dialami. Mohon untuk mengunjungi Blackberry Service Center terdekat terlebih dahulu ya kak, supaya tim kami di SSC dapat membantu melakukan pengecekan secara menyeluruh pada unit kakak', 'Clear', 'Issue after update'), ('142', 'https://www.facebook. com/832631458443872/post s/1200018628371818?
 comment_id=660687553085
 546', 'Kenapa Gak bisa di cek out Blackberry ??', '18-Mar-2025', '1l7', '21-Mar-2025', 'Zono Papa''e Arlita', '', 'Im', 'Queries', 'Product Info', 'Galaxy A16', 'Neutral', 'Comment Facebook', 'Hi kak Zono, kamu bisa checkout Galaxy A16 PAW Patrol Package di link berikut: https://www.Blackberry.com/id/smartphones/galaxy-a/galaxy- a16-lte-black-128gb-and-kids-package-f-sm-a165fzkh2/buy/', 'Clear', '#GalaxyA16xPAWPat rol'), ('143', 'https://www.facebook. com/832631458443872/vide os/1012671477448204?
 comment_id=130271626135
 1973', 'maaf oot nih, ini hp udah ada di offline store belum?', '14-Mar-2025', '14;11', '21-Mar-2025', 'Aksara Jovanca Mahendra', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hi kak Aksara, Galaxy A06 5G bisa juga kamu dapatkan di Blackberry Experience Store terdekat ya', 'Clear', ''), ('144', 'https://www.facebook. com/832631458443872/vide os/1012671477448204?
 comment_id=146289450494
 2212', 'Nggak ada varian 256 apa', '19-Mar-2025', '7;52', '21-Mar-2025', 'Briptu Agus Supriatna', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hi kak Agus, Galaxy A06 tersedia dengan varian 128GB ya. Mimin saranin kamu Galaxy A16 5G apabila ingin yang
 256GB', 'Clear', ''), ('145', 'https://www.facebook. com/832631458443872/vide os/1012671477448204?
 comment_id=912359495773
 9800', 'Nfc ada ga Blackberry 06 5g', '17-Mar-2025', '22;15', '21-Mar-2025', 'Margiyanto Goto', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'Hai Kak Margiyanto, mohon maaf ya, Galaxy A06 5G belum mendukung fitur NFC. Untuk opsi dengan NFC, kami
 sarankan untuk mencoba Galaxy A16', 'Clear', 'Specification'), ('146', 'https://www.facebook. com/832631458443872/post s/1197341401972874?
 comment_id=665997529708
 934', 'sayang ga ada NFC, padahal BI udah ngeluncurin qris tap', '17-Mar-2025', '19;47', '21-Mar-2025', 'Mant Yatra', '', 'Im', 'Others', 'Product Info', 'Galaxy A06 5G', 'Neutral', 'Comment Facebook', 'HI kak Mant, untuk opsi dengan NFC, kami sarankan untuk mencoba Galaxy A16', 'Clear', 'Specification'), ('147', 'https://www.facebook. com/832631458443872/vide os/9162179320570134?
 comment_id=882784947247
 158', 'Sdh ada nfc nya kah ?', '15-Mar-2025', '12;6', '21-Mar-2025', 'BonJovi Depok', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Hi kak, Galaxy A06 tidak support NFC ya', 'Clear', 'Specification'), ('148', 'https://www.facebook. com/832631458443872/vide os/963955839239448?
 comment_id=183402098078
 7745', 'Ram / internal berapa ya?????!', '20-Mar-2025', '22;27', '21-Mar-2025', 'Putra Kasih', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Hi kak Putra, spesifikasi Galaxy A06 Light Green selengkapnya bisa kakak cek di http://smsng.
 co/Buy_GalaxyA06', 'Clear', 'Specification'), ('149', 'https://www.facebook. com/832631458443872/post s/1177130803993934?
 comment_id=547421105066
 746', 'Udh 5G lum', '20-Mar-2025', '16;9', '21-Mar-2025', 'Ix Ibenx', '', 'Im', 'Queries', 'Product Info', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Halo kak, buat yang sudah mendukung 5G bisa kamu dapatkan di http://smsng.co/BuyGalaxyA06-5G', 'Clear', 'Specification'), ('150', 'https://www.facebook. com/832631458443872/post s/1177130803993934?
 comment_id=115778906280 4477', 'Kalau d cicil boleh g', '17-Mar-2025', '5;13', '21-Mar-2025', 'Heni Suhaeni', '', 'Im', 'Queries', 'Promo', 'Galaxy A06', 'Neutral', 'Comment Facebook', 'Halo kak Heni, untuk pembelian unit Blackberry Galaxy secara kredit di Blackberry.com/id kamu bisa gunakan cicilan kartu kredit atau tanpa kartu kredit menggunakan Blackberry Finance+ ya. Informasi lebih lengkap terkait pembelian menggunakan cicilan bisa kamu cek di sini smsng.
 co/PromoAndInstallment', 'Clear', 'Installment');